
INSERT ALL
INTO PERSONAL_INFORMATION (ID_client , FIRSTNAME, LASTNAME, PHONE, ADDRESS, CITIZENSHIP, AGE, MARITAL_STATUS, CHILDREN)
VALUES  ( 2, 'VLADISLAV', 'STAMENOV', '001888333555', 'VARNA', 'BULGARIAN', 25, 'SINGLE', 0)
INTO PERSONAL_INFORMATION (ID_client , FIRSTNAME, LASTNAME, PHONE, ADDRESS, CITIZENSHIP, AGE, MARITAL_STATUS, CHILDREN)
VALUES  ( 3 ,'IVAN', 'HADJIEV', '001888336665', 'SOFIA', 'BULGARIAN', 27, 'MARRIED', 2)
INTO PERSONAL_INFORMATION (ID_client , FIRSTNAME, LASTNAME, PHONE, ADDRESS, CITIZENSHIP, AGE, MARITAL_STATUS, CHILDREN)
VALUES  ( 15 ,'PETAR', 'PETROV', '0019912345', 'SOFIA', 'BULGARIAN', 33, 'SINGLE', 0)
SELECT * FROM DUAL;


INSERT INTO FINANCIAL_STATUS (ID_Client , JOB_POSITION, TYPE_OF_CONTRACT , MONTHLY_SALARY, OTHER_INCOMES, OTHER_LOANS)
VALUES  ( 2, 'DEV_OPS', 'PERMANENT', 2500 , 0, 200);
INSERT INTO FINANCIAL_STATUS (ID_Client , JOB_POSITION, TYPE_OF_CONTRACT , MONTHLY_SALARY, OTHER_INCOMES, OTHER_LOANS)
VALUES  ( 15, 'MANAGER', 'PERMANENT', 8000 , 100, 0);

INSERT INTO BANK_OFFER (ID_CLIENT, MIN_AMOUNT, MAX_AMOUNT, MIN_MONTHS, MAX_MONTHS, INTEREST)
VALUES(2, 10000, 40000, 60, 120, 3.5);
INSERT INTO BANK_OFFER (ID_CLIENT, MIN_AMOUNT, MAX_AMOUNT, MIN_MONTHS, MAX_MONTHS, INTEREST)
VALUES(1, 10000, 40000, 60, 120, 3.5);
INSERT INTO BANK_OFFER (ID_CLIENT, MIN_AMOUNT, MAX_AMOUNT, MIN_MONTHS, MAX_MONTHS, INTEREST)
VALUES(15, 10000, 50000, 60, 120, 3.5);

INSERT INTO BANK_OFFER_RESPONSE(ID_CLIENT, AMOUNT, MONTHS)
VALUES (15, 30000, 70);

INSERT INTO REGISTRATION_TOKEN (ID_CLIENT, TOKEN) VALUES (3, '17f018a7-5bef-4e83-bd45-e4ce5591a912');
INSERT INTO REGISTRATION_TOKEN (ID_CLIENT, TOKEN) VALUES (2, 'ec53f378-d904-4be6-9abe-ab017dded1df');
INSERT INTO REGISTRATION_TOKEN (ID_CLIENT, TOKEN) VALUES (15, 'ec53f378-d904-4be6-9abe-ab017dded2as');

INSERT INTO REGISTRATION_FORM (ID_CLIENT, USERNAME, PASSWORD, ROLE) VALUES (2, 'Vladislav', 'Iampassword', 'USER');
INSERT INTO REGISTRATION_FORM (ID_CLIENT, USERNAME, PASSWORD, ROLE) VALUES (15, 'Petar', 'Iampassword1', 'USER');